### ISSUE TITLE
udev and systemd merger

### ISSUE THREAD

**Issue by shearl** [LudovicRousseau/PCSC#2]
According to the linux-hotplug mailing list, udev and systemd have merged: http://lwn.net/Articles/490413/

When udev support isn't found, the pcsc-lite configure script suggests the following options:
`install libudev-dev or use --disable-libudev`

I think due to the merger `libudev-dev` is no longer available??

At least on the [Pulsar Linux](http://www.windriver.com/products/operating-systems/pulsar/) distribution I'm using, `libudev-dev` is not available through the so-called [smart package manager](https://labix.org/smart). After discovering that udev and system have merged, I tried installing the package `systemd-dev` and was able to build and successfully use pcsc-lite + ccid. (But perhaps it was many of the dependencies installed by `systemd-dev` that did the trick?)

So I think the suggestions in the configure script should be updated to something like:
`install libudev-dev (or systemd-dev* for systems with systemd >= 184) or use --disable-libudev`

If that's correct, I can commit a pull request if you like.

Or perhaps the configure script can look for either option? (I'm not a configure script expert.)

*Though on other distributions the package might be named libsystemd-dev or systemd-devel.

**Comment by LudovicRousseau** [comment]
Debian provides systemd version 228 and libudev-dev is still provided.
libsystemd-dev does not provide the pkg-config file libudev.pc used by the check in configure.

Packages names and content will depend on every Linux distribution. I do not plan to write a complete INSTALL documentation in the configure error message. I don't think this proposal is a good idea.

As a developer building pcsc-lite you should be smart enough to know what package to install :-)

**Comment by Jean-Baptiste-Lasselle** [comment]
> According to the linux-hotplug mailing list, udev and systemd have merged: http://lwn.net/Articles/490413/
> 
> When udev support isn't found, the pcsc-lite configure script suggests the following options:
> `install libudev-dev or use --disable-libudev`
> 
> I think due to the merger `libudev-dev` is no longer available??
> 
> At least on the [Pulsar Linux](http://www.windriver.com/products/operating-systems/pulsar/) distribution I'm using, `libudev-dev` is not available through the so-called [smart package manager](https://labix.org/smart). After discovering that udev and system have merged, I tried installing the package `systemd-dev` and was able to build and successfully use pcsc-lite + ccid. (But perhaps it was many of the dependencies installed by `systemd-dev` that did the trick?)
> 
> So I think the suggestions in the configure script should be updated to something like:
> `install libudev-dev (or systemd-dev* for systems with systemd >= 184) or use --disable-libudev`
> 
> If that's correct, I can commit a pull request if you like.
> 
> Or perhaps the configure script can look for either option? (I'm not a configure script expert.)
> 
> *Though on other distributions the package might be named libsystemd-dev or systemd-devel.

Oh My, thank you so much  @shearl , I am currently working on setting up a special K8S cluster, running a very specific App, using Smart Cards, so I have to provision labeled smart-card-enablded" K8S cluster nodes, and damn : 
If I finally di not end up on your question here, I would nbever have been able to install `pc sc lite` package to finally make my Smart Card drivers work,   so thank you SO MUCH, for this question and your infos ! 

Details : 
I setup my prototype using Debian Stretch, and Oh My, I ran into a `Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory` error....

So I installed `pc sc lite` package, to get the driver in my system, so I can go back to real serious wokr in `K8S`. And I foolowed the following recipe (which worked thanks to you @shearl :+1: ) : 

```bash
export OPS_HOME=~/.ethereum-test
export PACKAGE_SOURCE_GIT_URI=https://salsa.debian.org/debian/pcsc-lite.git

mkdir -p $OPS_HOME/.pcsc-lite
cd $OPS_HOME/.pcsc-lite
git clone "$PACKAGE_SOURCE_GIT_URI" .

# Briefly, the shell command './configure && make && make install'  should configure, build, AND install this package.
# see. https://salsa.debian.org/debian/pcsc-lite/blob/master/INSTALL

sudo apt-get install -y systemd-dev*
sudo ./configure && sudo make && sudo make install
```

at any rate @shearl , if you're curious what I was working on : https://github.com/Jean-Baptiste-Lasselle/ethereum-test/edit/master/README.md



Well I do need that driver installed, it is a hardware requirements from the app I am using, so here is a case @LudovicRousseau , where, I think you might be a bit harsh with us, there : 

No, I don't think that only developers should be able to solve that problem, because build from source, is the only way I found to provision the `pc sc lite` driver  inside my OS.

@LudovicRousseau Vous trouverez même uune preuve de sincérité : https://github.com/Jean-Baptiste-Lasselle/ethereum-test/edit/master/README.md 
vous pourrez y lire que je m'atttendais à vous devoir un énorme merci.

Je vous le transmets, parce que sans votre travail, je n'aurais rien trouvé, mais suis en désaccord avec vous sur cette vision du "tu es développeur, tu dois savoir débogguer ça tout seul, même si la doc n'indique rien"...

**Comment by LudovicRousseau** [comment]
@Jean-Baptiste-Lasselle No need to rebuild pcsc-lite from source code. Just install the `pcscd` package on a Debian system.
Also no need to run `./configure` and `make` with `sudo`. It is a dangerous idea. Please do not document that in your https://github.com/Jean-Baptiste-Lasselle/ethereum-test/blob/master/README.md.

@shearl On Debian the `libudev-dev` package is still provided and will be for some more time I think. I can't give the package name for every existing GNU/Linux distribution. Sorry for that. I ask the user to be smart.
